package TrafficDescription;

/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2018-05-17")
public class NowAreaTrafficData implements org.apache.thrift.TBase<NowAreaTrafficData, NowAreaTrafficData._Fields>, java.io.Serializable, Cloneable, Comparable<NowAreaTrafficData> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TrafficDescription.NowAreaTrafficData");

  private static final org.apache.thrift.protocol.TField AREA_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("areaId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField TIME_OF_HOUR_FIELD_DESC = new org.apache.thrift.protocol.TField("timeOfHour", org.apache.thrift.protocol.TType.DOUBLE, (short)2);
  private static final org.apache.thrift.protocol.TField NOW_AREA_TRAFFIC_FIELD_DESC = new org.apache.thrift.protocol.TField("nowAreaTraffic", org.apache.thrift.protocol.TType.LIST, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new NowAreaTrafficDataStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new NowAreaTrafficDataTupleSchemeFactory();

  public java.lang.String areaId; // required
  public double timeOfHour; // required
  public java.util.List<java.lang.Double> nowAreaTraffic; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    AREA_ID((short)1, "areaId"),
    TIME_OF_HOUR((short)2, "timeOfHour"),
    NOW_AREA_TRAFFIC((short)3, "nowAreaTraffic");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // AREA_ID
          return AREA_ID;
        case 2: // TIME_OF_HOUR
          return TIME_OF_HOUR;
        case 3: // NOW_AREA_TRAFFIC
          return NOW_AREA_TRAFFIC;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TIMEOFHOUR_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.AREA_ID, new org.apache.thrift.meta_data.FieldMetaData("areaId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TIME_OF_HOUR, new org.apache.thrift.meta_data.FieldMetaData("timeOfHour", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.NOW_AREA_TRAFFIC, new org.apache.thrift.meta_data.FieldMetaData("nowAreaTraffic", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(NowAreaTrafficData.class, metaDataMap);
  }

  public NowAreaTrafficData() {
  }

  public NowAreaTrafficData(
    java.lang.String areaId,
    double timeOfHour,
    java.util.List<java.lang.Double> nowAreaTraffic)
  {
    this();
    this.areaId = areaId;
    this.timeOfHour = timeOfHour;
    setTimeOfHourIsSet(true);
    this.nowAreaTraffic = nowAreaTraffic;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public NowAreaTrafficData(NowAreaTrafficData other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetAreaId()) {
      this.areaId = other.areaId;
    }
    this.timeOfHour = other.timeOfHour;
    if (other.isSetNowAreaTraffic()) {
      java.util.List<java.lang.Double> __this__nowAreaTraffic = new java.util.ArrayList<java.lang.Double>(other.nowAreaTraffic);
      this.nowAreaTraffic = __this__nowAreaTraffic;
    }
  }

  public NowAreaTrafficData deepCopy() {
    return new NowAreaTrafficData(this);
  }

  @Override
  public void clear() {
    this.areaId = null;
    setTimeOfHourIsSet(false);
    this.timeOfHour = 0.0;
    this.nowAreaTraffic = null;
  }

  public java.lang.String getAreaId() {
    return this.areaId;
  }

  public NowAreaTrafficData setAreaId(java.lang.String areaId) {
    this.areaId = areaId;
    return this;
  }

  public void unsetAreaId() {
    this.areaId = null;
  }

  /** Returns true if field areaId is set (has been assigned a value) and false otherwise */
  public boolean isSetAreaId() {
    return this.areaId != null;
  }

  public void setAreaIdIsSet(boolean value) {
    if (!value) {
      this.areaId = null;
    }
  }

  public double getTimeOfHour() {
    return this.timeOfHour;
  }

  public NowAreaTrafficData setTimeOfHour(double timeOfHour) {
    this.timeOfHour = timeOfHour;
    setTimeOfHourIsSet(true);
    return this;
  }

  public void unsetTimeOfHour() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TIMEOFHOUR_ISSET_ID);
  }

  /** Returns true if field timeOfHour is set (has been assigned a value) and false otherwise */
  public boolean isSetTimeOfHour() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TIMEOFHOUR_ISSET_ID);
  }

  public void setTimeOfHourIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TIMEOFHOUR_ISSET_ID, value);
  }

  public int getNowAreaTrafficSize() {
    return (this.nowAreaTraffic == null) ? 0 : this.nowAreaTraffic.size();
  }

  public java.util.Iterator<java.lang.Double> getNowAreaTrafficIterator() {
    return (this.nowAreaTraffic == null) ? null : this.nowAreaTraffic.iterator();
  }

  public void addToNowAreaTraffic(double elem) {
    if (this.nowAreaTraffic == null) {
      this.nowAreaTraffic = new java.util.ArrayList<java.lang.Double>();
    }
    this.nowAreaTraffic.add(elem);
  }

  public java.util.List<java.lang.Double> getNowAreaTraffic() {
    return this.nowAreaTraffic;
  }

  public NowAreaTrafficData setNowAreaTraffic(java.util.List<java.lang.Double> nowAreaTraffic) {
    this.nowAreaTraffic = nowAreaTraffic;
    return this;
  }

  public void unsetNowAreaTraffic() {
    this.nowAreaTraffic = null;
  }

  /** Returns true if field nowAreaTraffic is set (has been assigned a value) and false otherwise */
  public boolean isSetNowAreaTraffic() {
    return this.nowAreaTraffic != null;
  }

  public void setNowAreaTrafficIsSet(boolean value) {
    if (!value) {
      this.nowAreaTraffic = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case AREA_ID:
      if (value == null) {
        unsetAreaId();
      } else {
        setAreaId((java.lang.String)value);
      }
      break;

    case TIME_OF_HOUR:
      if (value == null) {
        unsetTimeOfHour();
      } else {
        setTimeOfHour((java.lang.Double)value);
      }
      break;

    case NOW_AREA_TRAFFIC:
      if (value == null) {
        unsetNowAreaTraffic();
      } else {
        setNowAreaTraffic((java.util.List<java.lang.Double>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case AREA_ID:
      return getAreaId();

    case TIME_OF_HOUR:
      return getTimeOfHour();

    case NOW_AREA_TRAFFIC:
      return getNowAreaTraffic();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case AREA_ID:
      return isSetAreaId();
    case TIME_OF_HOUR:
      return isSetTimeOfHour();
    case NOW_AREA_TRAFFIC:
      return isSetNowAreaTraffic();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof NowAreaTrafficData)
      return this.equals((NowAreaTrafficData)that);
    return false;
  }

  public boolean equals(NowAreaTrafficData that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_areaId = true && this.isSetAreaId();
    boolean that_present_areaId = true && that.isSetAreaId();
    if (this_present_areaId || that_present_areaId) {
      if (!(this_present_areaId && that_present_areaId))
        return false;
      if (!this.areaId.equals(that.areaId))
        return false;
    }

    boolean this_present_timeOfHour = true;
    boolean that_present_timeOfHour = true;
    if (this_present_timeOfHour || that_present_timeOfHour) {
      if (!(this_present_timeOfHour && that_present_timeOfHour))
        return false;
      if (this.timeOfHour != that.timeOfHour)
        return false;
    }

    boolean this_present_nowAreaTraffic = true && this.isSetNowAreaTraffic();
    boolean that_present_nowAreaTraffic = true && that.isSetNowAreaTraffic();
    if (this_present_nowAreaTraffic || that_present_nowAreaTraffic) {
      if (!(this_present_nowAreaTraffic && that_present_nowAreaTraffic))
        return false;
      if (!this.nowAreaTraffic.equals(that.nowAreaTraffic))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetAreaId()) ? 131071 : 524287);
    if (isSetAreaId())
      hashCode = hashCode * 8191 + areaId.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(timeOfHour);

    hashCode = hashCode * 8191 + ((isSetNowAreaTraffic()) ? 131071 : 524287);
    if (isSetNowAreaTraffic())
      hashCode = hashCode * 8191 + nowAreaTraffic.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(NowAreaTrafficData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetAreaId()).compareTo(other.isSetAreaId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAreaId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.areaId, other.areaId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetTimeOfHour()).compareTo(other.isSetTimeOfHour());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTimeOfHour()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.timeOfHour, other.timeOfHour);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetNowAreaTraffic()).compareTo(other.isSetNowAreaTraffic());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNowAreaTraffic()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nowAreaTraffic, other.nowAreaTraffic);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TrafficDescription.NowAreaTrafficData(");
    boolean first = true;

    sb.append("areaId:");
    if (this.areaId == null) {
      sb.append("null");
    } else {
      sb.append(this.areaId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("timeOfHour:");
    sb.append(this.timeOfHour);
    first = false;
    if (!first) sb.append(", ");
    sb.append("nowAreaTraffic:");
    if (this.nowAreaTraffic == null) {
      sb.append("null");
    } else {
      sb.append(this.nowAreaTraffic);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class NowAreaTrafficDataStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public NowAreaTrafficDataStandardScheme getScheme() {
      return new NowAreaTrafficDataStandardScheme();
    }
  }

  private static class NowAreaTrafficDataStandardScheme extends org.apache.thrift.scheme.StandardScheme<NowAreaTrafficData> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, NowAreaTrafficData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // AREA_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.areaId = iprot.readString();
              struct.setAreaIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TIME_OF_HOUR
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.timeOfHour = iprot.readDouble();
              struct.setTimeOfHourIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // NOW_AREA_TRAFFIC
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.nowAreaTraffic = new java.util.ArrayList<java.lang.Double>(_list0.size);
                double _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = iprot.readDouble();
                  struct.nowAreaTraffic.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setNowAreaTrafficIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, NowAreaTrafficData struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.areaId != null) {
        oprot.writeFieldBegin(AREA_ID_FIELD_DESC);
        oprot.writeString(struct.areaId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TIME_OF_HOUR_FIELD_DESC);
      oprot.writeDouble(struct.timeOfHour);
      oprot.writeFieldEnd();
      if (struct.nowAreaTraffic != null) {
        oprot.writeFieldBegin(NOW_AREA_TRAFFIC_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.DOUBLE, struct.nowAreaTraffic.size()));
          for (double _iter3 : struct.nowAreaTraffic)
          {
            oprot.writeDouble(_iter3);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class NowAreaTrafficDataTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public NowAreaTrafficDataTupleScheme getScheme() {
      return new NowAreaTrafficDataTupleScheme();
    }
  }

  private static class NowAreaTrafficDataTupleScheme extends org.apache.thrift.scheme.TupleScheme<NowAreaTrafficData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, NowAreaTrafficData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetAreaId()) {
        optionals.set(0);
      }
      if (struct.isSetTimeOfHour()) {
        optionals.set(1);
      }
      if (struct.isSetNowAreaTraffic()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetAreaId()) {
        oprot.writeString(struct.areaId);
      }
      if (struct.isSetTimeOfHour()) {
        oprot.writeDouble(struct.timeOfHour);
      }
      if (struct.isSetNowAreaTraffic()) {
        {
          oprot.writeI32(struct.nowAreaTraffic.size());
          for (double _iter4 : struct.nowAreaTraffic)
          {
            oprot.writeDouble(_iter4);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, NowAreaTrafficData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.areaId = iprot.readString();
        struct.setAreaIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.timeOfHour = iprot.readDouble();
        struct.setTimeOfHourIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.DOUBLE, iprot.readI32());
          struct.nowAreaTraffic = new java.util.ArrayList<java.lang.Double>(_list5.size);
          double _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = iprot.readDouble();
            struct.nowAreaTraffic.add(_elem6);
          }
        }
        struct.setNowAreaTrafficIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

