package TrafficDescription;

/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2018-05-17")
public class NowEdgeTrafficData implements org.apache.thrift.TBase<NowEdgeTrafficData, NowEdgeTrafficData._Fields>, java.io.Serializable, Cloneable, Comparable<NowEdgeTrafficData> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TrafficDescription.NowEdgeTrafficData");

  private static final org.apache.thrift.protocol.TField EDGE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("edgeId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField TIME_OF_HOUR_FIELD_DESC = new org.apache.thrift.protocol.TField("timeOfHour", org.apache.thrift.protocol.TType.DOUBLE, (short)2);
  private static final org.apache.thrift.protocol.TField NOW_EDGE_TRAFFIC_FIELD_DESC = new org.apache.thrift.protocol.TField("NowEdgeTraffic", org.apache.thrift.protocol.TType.LIST, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new NowEdgeTrafficDataStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new NowEdgeTrafficDataTupleSchemeFactory();

  public java.lang.String edgeId; // required
  public double timeOfHour; // required
  public java.util.List<java.lang.Double> NowEdgeTraffic; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    EDGE_ID((short)1, "edgeId"),
    TIME_OF_HOUR((short)2, "timeOfHour"),
    NOW_EDGE_TRAFFIC((short)3, "NowEdgeTraffic");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // EDGE_ID
          return EDGE_ID;
        case 2: // TIME_OF_HOUR
          return TIME_OF_HOUR;
        case 3: // NOW_EDGE_TRAFFIC
          return NOW_EDGE_TRAFFIC;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TIMEOFHOUR_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.EDGE_ID, new org.apache.thrift.meta_data.FieldMetaData("edgeId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TIME_OF_HOUR, new org.apache.thrift.meta_data.FieldMetaData("timeOfHour", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.NOW_EDGE_TRAFFIC, new org.apache.thrift.meta_data.FieldMetaData("NowEdgeTraffic", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(NowEdgeTrafficData.class, metaDataMap);
  }

  public NowEdgeTrafficData() {
  }

  public NowEdgeTrafficData(
    java.lang.String edgeId,
    double timeOfHour,
    java.util.List<java.lang.Double> NowEdgeTraffic)
  {
    this();
    this.edgeId = edgeId;
    this.timeOfHour = timeOfHour;
    setTimeOfHourIsSet(true);
    this.NowEdgeTraffic = NowEdgeTraffic;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public NowEdgeTrafficData(NowEdgeTrafficData other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetEdgeId()) {
      this.edgeId = other.edgeId;
    }
    this.timeOfHour = other.timeOfHour;
    if (other.isSetNowEdgeTraffic()) {
      java.util.List<java.lang.Double> __this__NowEdgeTraffic = new java.util.ArrayList<java.lang.Double>(other.NowEdgeTraffic);
      this.NowEdgeTraffic = __this__NowEdgeTraffic;
    }
  }

  public NowEdgeTrafficData deepCopy() {
    return new NowEdgeTrafficData(this);
  }

  @Override
  public void clear() {
    this.edgeId = null;
    setTimeOfHourIsSet(false);
    this.timeOfHour = 0.0;
    this.NowEdgeTraffic = null;
  }

  public java.lang.String getEdgeId() {
    return this.edgeId;
  }

  public NowEdgeTrafficData setEdgeId(java.lang.String edgeId) {
    this.edgeId = edgeId;
    return this;
  }

  public void unsetEdgeId() {
    this.edgeId = null;
  }

  /** Returns true if field edgeId is set (has been assigned a value) and false otherwise */
  public boolean isSetEdgeId() {
    return this.edgeId != null;
  }

  public void setEdgeIdIsSet(boolean value) {
    if (!value) {
      this.edgeId = null;
    }
  }

  public double getTimeOfHour() {
    return this.timeOfHour;
  }

  public NowEdgeTrafficData setTimeOfHour(double timeOfHour) {
    this.timeOfHour = timeOfHour;
    setTimeOfHourIsSet(true);
    return this;
  }

  public void unsetTimeOfHour() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TIMEOFHOUR_ISSET_ID);
  }

  /** Returns true if field timeOfHour is set (has been assigned a value) and false otherwise */
  public boolean isSetTimeOfHour() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TIMEOFHOUR_ISSET_ID);
  }

  public void setTimeOfHourIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TIMEOFHOUR_ISSET_ID, value);
  }

  public int getNowEdgeTrafficSize() {
    return (this.NowEdgeTraffic == null) ? 0 : this.NowEdgeTraffic.size();
  }

  public java.util.Iterator<java.lang.Double> getNowEdgeTrafficIterator() {
    return (this.NowEdgeTraffic == null) ? null : this.NowEdgeTraffic.iterator();
  }

  public void addToNowEdgeTraffic(double elem) {
    if (this.NowEdgeTraffic == null) {
      this.NowEdgeTraffic = new java.util.ArrayList<java.lang.Double>();
    }
    this.NowEdgeTraffic.add(elem);
  }

  public java.util.List<java.lang.Double> getNowEdgeTraffic() {
    return this.NowEdgeTraffic;
  }

  public NowEdgeTrafficData setNowEdgeTraffic(java.util.List<java.lang.Double> NowEdgeTraffic) {
    this.NowEdgeTraffic = NowEdgeTraffic;
    return this;
  }

  public void unsetNowEdgeTraffic() {
    this.NowEdgeTraffic = null;
  }

  /** Returns true if field NowEdgeTraffic is set (has been assigned a value) and false otherwise */
  public boolean isSetNowEdgeTraffic() {
    return this.NowEdgeTraffic != null;
  }

  public void setNowEdgeTrafficIsSet(boolean value) {
    if (!value) {
      this.NowEdgeTraffic = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case EDGE_ID:
      if (value == null) {
        unsetEdgeId();
      } else {
        setEdgeId((java.lang.String)value);
      }
      break;

    case TIME_OF_HOUR:
      if (value == null) {
        unsetTimeOfHour();
      } else {
        setTimeOfHour((java.lang.Double)value);
      }
      break;

    case NOW_EDGE_TRAFFIC:
      if (value == null) {
        unsetNowEdgeTraffic();
      } else {
        setNowEdgeTraffic((java.util.List<java.lang.Double>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case EDGE_ID:
      return getEdgeId();

    case TIME_OF_HOUR:
      return getTimeOfHour();

    case NOW_EDGE_TRAFFIC:
      return getNowEdgeTraffic();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case EDGE_ID:
      return isSetEdgeId();
    case TIME_OF_HOUR:
      return isSetTimeOfHour();
    case NOW_EDGE_TRAFFIC:
      return isSetNowEdgeTraffic();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof NowEdgeTrafficData)
      return this.equals((NowEdgeTrafficData)that);
    return false;
  }

  public boolean equals(NowEdgeTrafficData that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_edgeId = true && this.isSetEdgeId();
    boolean that_present_edgeId = true && that.isSetEdgeId();
    if (this_present_edgeId || that_present_edgeId) {
      if (!(this_present_edgeId && that_present_edgeId))
        return false;
      if (!this.edgeId.equals(that.edgeId))
        return false;
    }

    boolean this_present_timeOfHour = true;
    boolean that_present_timeOfHour = true;
    if (this_present_timeOfHour || that_present_timeOfHour) {
      if (!(this_present_timeOfHour && that_present_timeOfHour))
        return false;
      if (this.timeOfHour != that.timeOfHour)
        return false;
    }

    boolean this_present_NowEdgeTraffic = true && this.isSetNowEdgeTraffic();
    boolean that_present_NowEdgeTraffic = true && that.isSetNowEdgeTraffic();
    if (this_present_NowEdgeTraffic || that_present_NowEdgeTraffic) {
      if (!(this_present_NowEdgeTraffic && that_present_NowEdgeTraffic))
        return false;
      if (!this.NowEdgeTraffic.equals(that.NowEdgeTraffic))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetEdgeId()) ? 131071 : 524287);
    if (isSetEdgeId())
      hashCode = hashCode * 8191 + edgeId.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(timeOfHour);

    hashCode = hashCode * 8191 + ((isSetNowEdgeTraffic()) ? 131071 : 524287);
    if (isSetNowEdgeTraffic())
      hashCode = hashCode * 8191 + NowEdgeTraffic.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(NowEdgeTrafficData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetEdgeId()).compareTo(other.isSetEdgeId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEdgeId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.edgeId, other.edgeId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetTimeOfHour()).compareTo(other.isSetTimeOfHour());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTimeOfHour()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.timeOfHour, other.timeOfHour);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetNowEdgeTraffic()).compareTo(other.isSetNowEdgeTraffic());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNowEdgeTraffic()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.NowEdgeTraffic, other.NowEdgeTraffic);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TrafficDescription.NowEdgeTrafficData(");
    boolean first = true;

    sb.append("edgeId:");
    if (this.edgeId == null) {
      sb.append("null");
    } else {
      sb.append(this.edgeId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("timeOfHour:");
    sb.append(this.timeOfHour);
    first = false;
    if (!first) sb.append(", ");
    sb.append("NowEdgeTraffic:");
    if (this.NowEdgeTraffic == null) {
      sb.append("null");
    } else {
      sb.append(this.NowEdgeTraffic);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class NowEdgeTrafficDataStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public NowEdgeTrafficDataStandardScheme getScheme() {
      return new NowEdgeTrafficDataStandardScheme();
    }
  }

  private static class NowEdgeTrafficDataStandardScheme extends org.apache.thrift.scheme.StandardScheme<NowEdgeTrafficData> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, NowEdgeTrafficData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // EDGE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.edgeId = iprot.readString();
              struct.setEdgeIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TIME_OF_HOUR
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.timeOfHour = iprot.readDouble();
              struct.setTimeOfHourIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // NOW_EDGE_TRAFFIC
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list16 = iprot.readListBegin();
                struct.NowEdgeTraffic = new java.util.ArrayList<java.lang.Double>(_list16.size);
                double _elem17;
                for (int _i18 = 0; _i18 < _list16.size; ++_i18)
                {
                  _elem17 = iprot.readDouble();
                  struct.NowEdgeTraffic.add(_elem17);
                }
                iprot.readListEnd();
              }
              struct.setNowEdgeTrafficIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, NowEdgeTrafficData struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.edgeId != null) {
        oprot.writeFieldBegin(EDGE_ID_FIELD_DESC);
        oprot.writeString(struct.edgeId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TIME_OF_HOUR_FIELD_DESC);
      oprot.writeDouble(struct.timeOfHour);
      oprot.writeFieldEnd();
      if (struct.NowEdgeTraffic != null) {
        oprot.writeFieldBegin(NOW_EDGE_TRAFFIC_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.DOUBLE, struct.NowEdgeTraffic.size()));
          for (double _iter19 : struct.NowEdgeTraffic)
          {
            oprot.writeDouble(_iter19);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class NowEdgeTrafficDataTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public NowEdgeTrafficDataTupleScheme getScheme() {
      return new NowEdgeTrafficDataTupleScheme();
    }
  }

  private static class NowEdgeTrafficDataTupleScheme extends org.apache.thrift.scheme.TupleScheme<NowEdgeTrafficData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, NowEdgeTrafficData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetEdgeId()) {
        optionals.set(0);
      }
      if (struct.isSetTimeOfHour()) {
        optionals.set(1);
      }
      if (struct.isSetNowEdgeTraffic()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetEdgeId()) {
        oprot.writeString(struct.edgeId);
      }
      if (struct.isSetTimeOfHour()) {
        oprot.writeDouble(struct.timeOfHour);
      }
      if (struct.isSetNowEdgeTraffic()) {
        {
          oprot.writeI32(struct.NowEdgeTraffic.size());
          for (double _iter20 : struct.NowEdgeTraffic)
          {
            oprot.writeDouble(_iter20);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, NowEdgeTrafficData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.edgeId = iprot.readString();
        struct.setEdgeIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.timeOfHour = iprot.readDouble();
        struct.setTimeOfHourIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list21 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.DOUBLE, iprot.readI32());
          struct.NowEdgeTraffic = new java.util.ArrayList<java.lang.Double>(_list21.size);
          double _elem22;
          for (int _i23 = 0; _i23 < _list21.size; ++_i23)
          {
            _elem22 = iprot.readDouble();
            struct.NowEdgeTraffic.add(_elem22);
          }
        }
        struct.setNowEdgeTrafficIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

