package TrafficDescription;

/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2018-05-13")
public class PredictedEdgeTrafficData implements org.apache.thrift.TBase<PredictedEdgeTrafficData, PredictedEdgeTrafficData._Fields>, java.io.Serializable, Cloneable, Comparable<PredictedEdgeTrafficData> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TrafficDescription.PredictedEdgeTrafficData");

  private static final org.apache.thrift.protocol.TField MIGRATION_FIELD_DESC = new org.apache.thrift.protocol.TField("migration", org.apache.thrift.protocol.TType.DOUBLE, (short)1);
  private static final org.apache.thrift.protocol.TField PREDICTED_EDGE_TRAFFIC_FIELD_DESC = new org.apache.thrift.protocol.TField("predictedEdgeTraffic", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new PredictedEdgeTrafficDataStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new PredictedEdgeTrafficDataTupleSchemeFactory();

  public double migration; // required
  public java.util.List<java.lang.Double> predictedEdgeTraffic; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MIGRATION((short)1, "migration"),
    PREDICTED_EDGE_TRAFFIC((short)2, "predictedEdgeTraffic");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MIGRATION
          return MIGRATION;
        case 2: // PREDICTED_EDGE_TRAFFIC
          return PREDICTED_EDGE_TRAFFIC;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __MIGRATION_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MIGRATION, new org.apache.thrift.meta_data.FieldMetaData("migration", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.PREDICTED_EDGE_TRAFFIC, new org.apache.thrift.meta_data.FieldMetaData("predictedEdgeTraffic", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PredictedEdgeTrafficData.class, metaDataMap);
  }

  public PredictedEdgeTrafficData() {
  }

  public PredictedEdgeTrafficData(
    double migration,
    java.util.List<java.lang.Double> predictedEdgeTraffic)
  {
    this();
    this.migration = migration;
    setMigrationIsSet(true);
    this.predictedEdgeTraffic = predictedEdgeTraffic;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PredictedEdgeTrafficData(PredictedEdgeTrafficData other) {
    __isset_bitfield = other.__isset_bitfield;
    this.migration = other.migration;
    if (other.isSetPredictedEdgeTraffic()) {
      java.util.List<java.lang.Double> __this__predictedEdgeTraffic = new java.util.ArrayList<java.lang.Double>(other.predictedEdgeTraffic);
      this.predictedEdgeTraffic = __this__predictedEdgeTraffic;
    }
  }

  public PredictedEdgeTrafficData deepCopy() {
    return new PredictedEdgeTrafficData(this);
  }

  @Override
  public void clear() {
    setMigrationIsSet(false);
    this.migration = 0.0;
    this.predictedEdgeTraffic = null;
  }

  public double getMigration() {
    return this.migration;
  }

  public PredictedEdgeTrafficData setMigration(double migration) {
    this.migration = migration;
    setMigrationIsSet(true);
    return this;
  }

  public void unsetMigration() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __MIGRATION_ISSET_ID);
  }

  /** Returns true if field migration is set (has been assigned a value) and false otherwise */
  public boolean isSetMigration() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __MIGRATION_ISSET_ID);
  }

  public void setMigrationIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __MIGRATION_ISSET_ID, value);
  }

  public int getPredictedEdgeTrafficSize() {
    return (this.predictedEdgeTraffic == null) ? 0 : this.predictedEdgeTraffic.size();
  }

  public java.util.Iterator<java.lang.Double> getPredictedEdgeTrafficIterator() {
    return (this.predictedEdgeTraffic == null) ? null : this.predictedEdgeTraffic.iterator();
  }

  public void addToPredictedEdgeTraffic(double elem) {
    if (this.predictedEdgeTraffic == null) {
      this.predictedEdgeTraffic = new java.util.ArrayList<java.lang.Double>();
    }
    this.predictedEdgeTraffic.add(elem);
  }

  public java.util.List<java.lang.Double> getPredictedEdgeTraffic() {
    return this.predictedEdgeTraffic;
  }

  public PredictedEdgeTrafficData setPredictedEdgeTraffic(java.util.List<java.lang.Double> predictedEdgeTraffic) {
    this.predictedEdgeTraffic = predictedEdgeTraffic;
    return this;
  }

  public void unsetPredictedEdgeTraffic() {
    this.predictedEdgeTraffic = null;
  }

  /** Returns true if field predictedEdgeTraffic is set (has been assigned a value) and false otherwise */
  public boolean isSetPredictedEdgeTraffic() {
    return this.predictedEdgeTraffic != null;
  }

  public void setPredictedEdgeTrafficIsSet(boolean value) {
    if (!value) {
      this.predictedEdgeTraffic = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case MIGRATION:
      if (value == null) {
        unsetMigration();
      } else {
        setMigration((java.lang.Double)value);
      }
      break;

    case PREDICTED_EDGE_TRAFFIC:
      if (value == null) {
        unsetPredictedEdgeTraffic();
      } else {
        setPredictedEdgeTraffic((java.util.List<java.lang.Double>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case MIGRATION:
      return getMigration();

    case PREDICTED_EDGE_TRAFFIC:
      return getPredictedEdgeTraffic();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case MIGRATION:
      return isSetMigration();
    case PREDICTED_EDGE_TRAFFIC:
      return isSetPredictedEdgeTraffic();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof PredictedEdgeTrafficData)
      return this.equals((PredictedEdgeTrafficData)that);
    return false;
  }

  public boolean equals(PredictedEdgeTrafficData that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_migration = true;
    boolean that_present_migration = true;
    if (this_present_migration || that_present_migration) {
      if (!(this_present_migration && that_present_migration))
        return false;
      if (this.migration != that.migration)
        return false;
    }

    boolean this_present_predictedEdgeTraffic = true && this.isSetPredictedEdgeTraffic();
    boolean that_present_predictedEdgeTraffic = true && that.isSetPredictedEdgeTraffic();
    if (this_present_predictedEdgeTraffic || that_present_predictedEdgeTraffic) {
      if (!(this_present_predictedEdgeTraffic && that_present_predictedEdgeTraffic))
        return false;
      if (!this.predictedEdgeTraffic.equals(that.predictedEdgeTraffic))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(migration);

    hashCode = hashCode * 8191 + ((isSetPredictedEdgeTraffic()) ? 131071 : 524287);
    if (isSetPredictedEdgeTraffic())
      hashCode = hashCode * 8191 + predictedEdgeTraffic.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(PredictedEdgeTrafficData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetMigration()).compareTo(other.isSetMigration());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMigration()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.migration, other.migration);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPredictedEdgeTraffic()).compareTo(other.isSetPredictedEdgeTraffic());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPredictedEdgeTraffic()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.predictedEdgeTraffic, other.predictedEdgeTraffic);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TrafficDescription.PredictedEdgeTrafficData(");
    boolean first = true;

    sb.append("migration:");
    sb.append(this.migration);
    first = false;
    if (!first) sb.append(", ");
    sb.append("predictedEdgeTraffic:");
    if (this.predictedEdgeTraffic == null) {
      sb.append("null");
    } else {
      sb.append(this.predictedEdgeTraffic);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PredictedEdgeTrafficDataStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public PredictedEdgeTrafficDataStandardScheme getScheme() {
      return new PredictedEdgeTrafficDataStandardScheme();
    }
  }

  private static class PredictedEdgeTrafficDataStandardScheme extends org.apache.thrift.scheme.StandardScheme<PredictedEdgeTrafficData> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PredictedEdgeTrafficData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MIGRATION
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.migration = iprot.readDouble();
              struct.setMigrationIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PREDICTED_EDGE_TRAFFIC
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list24 = iprot.readListBegin();
                struct.predictedEdgeTraffic = new java.util.ArrayList<java.lang.Double>(_list24.size);
                double _elem25;
                for (int _i26 = 0; _i26 < _list24.size; ++_i26)
                {
                  _elem25 = iprot.readDouble();
                  struct.predictedEdgeTraffic.add(_elem25);
                }
                iprot.readListEnd();
              }
              struct.setPredictedEdgeTrafficIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PredictedEdgeTrafficData struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(MIGRATION_FIELD_DESC);
      oprot.writeDouble(struct.migration);
      oprot.writeFieldEnd();
      if (struct.predictedEdgeTraffic != null) {
        oprot.writeFieldBegin(PREDICTED_EDGE_TRAFFIC_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.DOUBLE, struct.predictedEdgeTraffic.size()));
          for (double _iter27 : struct.predictedEdgeTraffic)
          {
            oprot.writeDouble(_iter27);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PredictedEdgeTrafficDataTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public PredictedEdgeTrafficDataTupleScheme getScheme() {
      return new PredictedEdgeTrafficDataTupleScheme();
    }
  }

  private static class PredictedEdgeTrafficDataTupleScheme extends org.apache.thrift.scheme.TupleScheme<PredictedEdgeTrafficData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PredictedEdgeTrafficData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetMigration()) {
        optionals.set(0);
      }
      if (struct.isSetPredictedEdgeTraffic()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetMigration()) {
        oprot.writeDouble(struct.migration);
      }
      if (struct.isSetPredictedEdgeTraffic()) {
        {
          oprot.writeI32(struct.predictedEdgeTraffic.size());
          for (double _iter28 : struct.predictedEdgeTraffic)
          {
            oprot.writeDouble(_iter28);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PredictedEdgeTrafficData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.migration = iprot.readDouble();
        struct.setMigrationIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list29 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.DOUBLE, iprot.readI32());
          struct.predictedEdgeTraffic = new java.util.ArrayList<java.lang.Double>(_list29.size);
          double _elem30;
          for (int _i31 = 0; _i31 < _list29.size; ++_i31)
          {
            _elem30 = iprot.readDouble();
            struct.predictedEdgeTraffic.add(_elem30);
          }
        }
        struct.setPredictedEdgeTrafficIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

